[package]
name = "jss"
version = "0.1.0"
authors = ["Anton Shramko <antonshramko@yandex.ru>"]

[features]
default = []
webrender_support = []

[dependencies]
webrender = { rev = "2e381e0325f367429810099d5abf76e674f697ed", git = "https://github.com/servo/webrender", optional = true }
palette = { version = "0.4", optional = true }

yoga = { git = "https://github.com/rise-ui/yoga-rs", features = ["serde_support"] }
prepare-style-derive = { path = "./prepare-style-derive" }
ordered-float = "0.5.0"
failure_derive = "0.1"
serde_derive = "1.0"
serde_json = "1.0"
failure = "0.1"
serde = "1.0"
regex = "0.2"
css-color-parser = "*"