[package]
name = "jss"
version = "0.1.0"
authors = ["Anton Shramko <antonshramko@yandex.ru>"]
repository = "https://github.com/rise-ui/jss-rs"
homepage = "https://github.com/rise-ui/jss-rs"
description = "Rust implementation of JSS"
keywords = ["gui", "layout", "yoga", "jss", "parsing"]
categories = ["gui"]
license = "MIT"

[features]
default = []
webrender_support = []

[workspace]

[dependencies]
webrender = { rev = "2e381e0325f367429810099d5abf76e674f697ed", git = "https://github.com/servo/webrender" }
yoga = { git = "https://github.com/rise-ui/yoga-rs", features = ["serde_support"] }
prepare-style-derive = { path = "prepare-style-derive", version = "0.1.0" }
ordered-float = "0.5.0"
css-color-parser = "*"
failure_derive = "0.1"
enum_extract = "0.1"
serde_derive = "1.0"
lazy_static = "1.0"
serde_json = "1.0"
failure = "0.1"
serde = "1.0"
regex = "0.2"
nom = "4.0"